# Generated by Django 4.2.11 on 2024-03-18 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forgefitnessweb', '0002_commentreview_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreview',
            options={},
        ),
        migrations.RemoveField(
            model_name='commentreview',
            name='image',
        ),
        migrations.AddField(
            model_name='commentreview',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forgefitnessweb.sessions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentreview',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
