# Generated by Django 4.2.11 on 2024-03-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgefitnessweb', '0002_classes_remove_profile_email_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Sessions',
        ),
    ]
