# Generated by Django 4.2.11 on 2024-03-21 14:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('forgefitnessweb', '0003_anoncontact_alter_commentreview_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.CharField(default='', null=True),
        ),
    ]
