# Generated by Django 4.2.11 on 2024-03-18 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forgefitnessweb', '0003_rename_classes_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
