# Generated by Django 4.2.11 on 2024-03-19 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forgefitnessweb', '0003_alter_commentreview_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreview',
            old_name='content',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='commentreview',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
